trigger: none

pool: infrapool

steps:

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
    backendServiceArm: 'INFRASVN'
    backendAzureRmStorageAccountName: 'blraccountstgsss'
    backendAzureRmContainerName: 'sigmaaccc'
    backendAzureRmKey: 'sigma.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
    environmentServiceNameAzureRM: 'INFRASVN'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
    environmentServiceNameAzureRM: 'INFRASVN'
